---
abstract: 'Perl interface to Amazon Marketplace Web Services'
author:
  - 'Avishai Goldman <veesh@cpan.org>'
  - 'Paul Driver <paul@plainblack.com>'
  - 'Phil Smith <phil.smith@rsdvd.com>'
  - 'Marco Pessotto <melmothx@gmail.com>'
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  DBD::SQLite: '0'
  DBI: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  HTTP::Response: '0'
  Test::Deep: '0'
  Test::MockObject: '0'
  Test::MockObject::Extends: '0'
  Test::More: '0'
  Test::Warnings: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amazon-MWS
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Amazon::MWS:
    file: lib/Amazon/MWS.pm
    version: '0.150'
  Amazon::MWS::AmazonPay:
    file: lib/Amazon/MWS/AmazonPay.pm
    version: '0.150'
  Amazon::MWS::Client:
    file: lib/Amazon/MWS/Client.pm
    version: '0.150'
  Amazon::MWS::Enumeration:
    file: lib/Amazon/MWS/Enumeration.pm
    version: '0.150'
  Amazon::MWS::Enumeration::FeedProcessingStatus:
    file: lib/Amazon/MWS/Enumeration/FeedProcessingStatus.pm
    version: '0.150'
  Amazon::MWS::Enumeration::FeedType:
    file: lib/Amazon/MWS/Enumeration/FeedType.pm
    version: '0.150'
  Amazon::MWS::Enumeration::ReportProcessingStatus:
    file: lib/Amazon/MWS/Enumeration/ReportProcessingStatus.pm
    version: '0.150'
  Amazon::MWS::Enumeration::ReportType:
    file: lib/Amazon/MWS/Enumeration/ReportType.pm
    version: '0.150'
  Amazon::MWS::Enumeration::Schedule:
    file: lib/Amazon/MWS/Enumeration/Schedule.pm
    version: '0.150'
  Amazon::MWS::Exception:
    file: lib/Amazon/MWS/Exception.pm
    version: '0.150'
  Amazon::MWS::Feeds:
    file: lib/Amazon/MWS/Feeds.pm
    version: '0.150'
  Amazon::MWS::Finances:
    file: lib/Amazon/MWS/Finances.pm
    version: '0.150'
  Amazon::MWS::FulfillmentInventory:
    file: lib/Amazon/MWS/FulfillmentInventory.pm
    version: '0.150'
  Amazon::MWS::FulfillmentOutbound:
    file: lib/Amazon/MWS/FulfillmentOutbound.pm
    version: '0.150'
  Amazon::MWS::InboundShipment:
    file: lib/Amazon/MWS/InboundShipment.pm
    version: '0.150'
  Amazon::MWS::Orders:
    file: lib/Amazon/MWS/Orders.pm
    version: '0.150'
  Amazon::MWS::Products:
    file: lib/Amazon/MWS/Products.pm
    version: '0.150'
  Amazon::MWS::Reports:
    file: lib/Amazon/MWS/Reports.pm
    version: '0.150'
  Amazon::MWS::Routines:
    file: lib/Amazon/MWS/Routines.pm
    version: '0.150'
  Amazon::MWS::Sellers:
    file: lib/Amazon/MWS/Sellers.pm
    version: '0.150'
  Amazon::MWS::TypeMap:
    file: lib/Amazon/MWS/TypeMap.pm
    version: '0.150'
  Amazon::MWS::Uploader:
    file: lib/Amazon/MWS/Uploader.pm
    version: '0.150'
  Amazon::MWS::XML::Address:
    file: lib/Amazon/MWS/XML/Address.pm
    version: '0.150'
  Amazon::MWS::XML::Feed:
    file: lib/Amazon/MWS/XML/Feed.pm
    version: '0.150'
  Amazon::MWS::XML::GenericFeed:
    file: lib/Amazon/MWS/XML/GenericFeed.pm
    version: '0.150'
  Amazon::MWS::XML::Order:
    file: lib/Amazon/MWS/XML/Order.pm
    version: '0.150'
  Amazon::MWS::XML::OrderlineItem:
    file: lib/Amazon/MWS/XML/OrderlineItem.pm
    version: '0.150'
  Amazon::MWS::XML::Product:
    file: lib/Amazon/MWS/XML/Product.pm
    version: '0.150'
  Amazon::MWS::XML::Response::FeedSubmissionResult:
    file: lib/Amazon/MWS/XML/Response/FeedSubmissionResult.pm
    version: '0.150'
  Amazon::MWS::XML::Response::OrderReport:
    file: lib/Amazon/MWS/XML/Response/OrderReport.pm
    version: '0.150'
  Amazon::MWS::XML::Response::OrderReport::Item:
    file: lib/Amazon/MWS/XML/Response/OrderReport/Item.pm
    version: '0.150'
  Amazon::MWS::XML::ShippedOrder:
    file: lib/Amazon/MWS/XML/ShippedOrder.pm
    version: '0.150'
requires:
  Class::InsideOut: '0'
  DBI: '0'
  DateTime: '0'
  DateTime::Formate::ISO8601: '0'
  Digest::HMAC_SHA1: '0'
  Digest::MD5: '0'
  Exception::Class: '0'
  Exporter: '0'
  HTTP::Request: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Moo: '0'
  MooX::Types::MooseLike: '0'
  Path::Tiny: '0'
  Readonly: '0'
  SQL::Abstract: '0'
  Try::Tiny: '0'
  URI: '0'
  URI::Escape: '0'
  XML::Compile: '0'
  XML::LibXML::Simple: '0'
  XML::Simple: '0'
  namespace::clean: '0'
version: '0.150'
x_Dist_Zilla:
  perl:
    version: '5.032000'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: '@Starter::Git/Git::GatherDir'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Starter::Git/MetaYAML'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Starter::Git/MetaJSON'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Starter::Git/License'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Starter::Git/PodSyntaxTests'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Starter::Git/Test::ReportPrereqs'
      version: '0.028'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: develop
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Starter::Git/Test::Compile'
      version: '2.058'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Starter::Git/PruneCruft'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Starter::Git/ManifestSkip'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter::Git/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
      name: '@Starter::Git/Git::Check'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::RewriteVersion
      config:
        Dist::Zilla::Plugin::RewriteVersion:
          add_tarball_name: 0
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          skip_version_provider: 0
      name: '@Starter::Git/RewriteVersion'
      version: '0.018'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Starter::Git/NextRelease'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in:
            - /
          commit_msg: '%v%n%n%c'
          signoff: '0'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Starter::Git/Release_Commit'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: '0.150'
          tag_format: '%v'
          tag_message: '%v'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Starter::Git/Git::Tag'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      config:
        Dist::Zilla::Plugin::BumpVersionAfterRelease:
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          munge_makefile_pl: 1
      name: '@Starter::Git/BumpVersionAfterRelease'
      version: '0.018'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: 'Bump version'
          signoff: '0'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match:
            - (?^:^)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Starter::Git/Version_Bump_Commit'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
      name: '@Starter::Git/Git::Push'
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Starter::Git/TestRelease'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Starter::Git/ConfirmRelease'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Starter::Git/MetaConfig'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Starter::Git/MetaNoIndex'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Starter::Git/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.017'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000037'
          version: '0.006'
      name: '@Starter::Git/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Starter::Git/ShareDir'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Starter::Git/ExecDir'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: build
          type: requires
      name: BuildRequires
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: ~
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.7.4
          repo_root: .
      name: Git::CommitBuild
      version: '2.047'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.017'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Starter::Git/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.017'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.017'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
